### ISSUE TITLE
Failed to set font family for code-editor

### ISSUE THREAD

**Issue by jwu** [fireball-packages/code-editor#6]
I try to setup the font family for code editor like this: https://github.com/fireball-packages/code-editor/commit/02c40b779529013e71a5a3f1acc345f09b5583c1 but failed. 

If I add font-family in .CodeMirror like this:

```css
.CodeMirror {
        height: 100%;
        font-size: 14px;
        font-family: 'DejaVu Sans Mono';
}
```

The font will be applied to code-mirror but the cursor will have wrong position.
